import { describe, expect, it } from "vitest";
import { buildUserExportPayload } from "@/lib/user/export";

describe("buildUserExportPayload", () => {
  it("maps database rows into stable export payload shape", () => {
    const payload = buildUserExportPayload({
      userId: "user-1",
      userEmail: "swimmer@example.com",
      generatedAt: "2026-02-17T12:00:00.000Z",
      profile: {
        id: "user-1",
        email: "swimmer@example.com",
        created_at: "2026-02-01T08:00:00.000Z",
        updated_at: "2026-02-10T08:00:00.000Z",
      },
      athleteProfile: {
        id: "athlete-profile-1",
        display_name: "Poolside Stian",
        first_name: "Stian",
        last_name: "Vikra",
        age_band: "35_44",
        created_at: "2026-03-19T08:00:00.000Z",
        updated_at: "2026-03-19T08:05:00.000Z",
      },
      trainingMetrics: [
        {
          id: "metric-1",
          metric_key: "css",
          unit: "seconds_per_100m",
          value_seconds: 118,
          recorded_on: "2026-03-19",
          source_note: "400 + 200 test",
          created_at: "2026-03-19T08:10:00.000Z",
          updated_at: "2026-03-19T08:11:00.000Z",
        },
      ],
      trainingPreferences: {
        id: "pref-1",
        pool_length_m: 25,
        available_days: ["monday", "wednesday"],
        preferred_weekly_session_count: 5,
        preferred_session_minutes: 60,
        created_at: "2026-03-19T08:12:00.000Z",
        updated_at: "2026-03-19T08:13:00.000Z",
      },
      personalRecords: [
        {
          id: "record-1",
          distance_m: 100,
          stroke: "freestyle",
          course: "pool_25m",
          time_centiseconds: 6234,
          recorded_on: "2026-03-19",
          source_note: "Club night",
          created_at: "2026-03-19T08:14:00.000Z",
          updated_at: "2026-03-19T08:15:00.000Z",
        },
      ],
      entitlements: [
        {
          id: "ent-1",
          product_id: "guide_0_1000m",
          purchaser_email: "swimmer@example.com",
          source: "stripe_checkout",
          stripe_customer_id: "cus_123",
          stripe_checkout_session_id: "cs_test_123",
          granted_at: "2026-02-11T08:00:00.000Z",
          created_at: "2026-02-11T08:00:00.000Z",
          updated_at: "2026-02-11T08:00:00.000Z",
        },
      ],
      courseProgress: [
        {
          lesson_id: "lesson-1",
          done: true,
          video_seconds: 120,
          updated_at: "2026-02-12T08:00:00.000Z",
        },
      ],
      guideProgress: [
        {
          guide_slug: "poolside",
          section_id: "d01",
          completed: true,
          notes: "felt smooth",
          updated_at: "2026-02-13T08:00:00.000Z",
        },
      ],
      guideSessionProgress: [
        {
          guide_slug: "0-1000m",
          session_number: 1,
          completed: true,
          notes: "solid pacing",
          completed_at: "2026-02-14T08:00:00.000Z",
          updated_at: "2026-02-14T08:10:00.000Z",
        },
      ],
      goals: [
        {
          id: "goal-1",
          title: "Swim 1000m",
          target_value: 1000,
          target_unit: "m",
          target_date: "2026-03-01",
          status: "active",
          celebrated_at: null,
          created_at: "2026-02-15T08:00:00.000Z",
          updated_at: "2026-02-15T08:00:00.000Z",
        },
      ],
      trainingFocuses: [
        {
          id: "focus-1",
          goal_id: "goal-1",
          title: "Longer exhale in the water",
          details: "Relax before rotating to breathe.",
          status: "open",
          is_primary: true,
          context_type: null,
          context_ref: null,
          completed_at: null,
          archived_at: null,
          created_at: "2026-03-19T08:00:00.000Z",
          updated_at: "2026-03-19T08:00:00.000Z",
        },
      ],
      trainingNotes: [
        {
          id: "note-1",
          goal_id: "goal-1",
          focus_id: "focus-1",
          note_type: "question",
          status: "answered",
          body: "Am I lifting my head before breathing?",
          answer: "Yes, keep one goggle in the water.",
          context_type: null,
          context_ref: null,
          resolved_at: "2026-03-19T08:05:00.000Z",
          created_at: "2026-03-19T08:00:00.000Z",
          updated_at: "2026-03-19T08:05:00.000Z",
        },
      ],
      downloadLinks: [
        {
          id: "dl-1",
          entitlement_id: "ent-1",
          expires_at: "2026-02-20T08:00:00.000Z",
          used_at: null,
          created_at: "2026-02-15T09:00:00.000Z",
        },
      ],
      drylandSessions: [
        {
          id: "dryland-1",
          source_kind: "manual",
          status: "draft",
          session_kind: "strength",
          title: "Core strength",
          description: "Short dryland session.",
          focus_text: "Brace the trunk first.",
          exercises: [
            {
              id: "exercise-1",
              title: "Plank",
              sets: [{ id: "set-1", holdSeconds: 45 }],
            },
          ],
          started_at: null,
          completed_at: null,
          actual_duration_seconds: null,
          created_at: "2026-05-08T08:00:00.000Z",
          updated_at: "2026-05-08T08:10:00.000Z",
        },
      ],
      habitDefinitions: [
        {
          id: "habit-1",
          title: "Quit chips",
          notes: null,
          habit_mode: "quit",
          habit_type: "avoidance",
          category: "nutrition",
          target_operator: "at_most",
          target_value_numeric: 0,
          target_unit: "times",
          target_time: null,
          start_date: "2026-05-09",
          last_lapse_date: null,
          timer_enabled: false,
          timer_target_seconds: null,
          cadence_period: "weekly",
          cadence_target_count: 2,
          cadence_day_policy: "fixed",
          schedule_days: ["monday", "tuesday"],
          is_perfect_day_item: true,
          status: "active",
          sort_order: 1,
          created_at: "2026-05-09T08:00:00.000Z",
          updated_at: "2026-05-09T08:10:00.000Z",
        },
      ],
      habitCheckIns: [
        {
          id: "habit-check-in-1",
          habit_id: "habit-1",
          check_in_date: "2026-05-10",
          timezone: "Europe/Oslo",
          value_numeric: null,
          value_boolean: false,
          value_time: null,
          note: null,
          status: "logged",
          source_kind: "micro_session",
          source_dryland_micro_plan_id: "22222222-2222-4222-8222-222222222222",
          source_micro_block_id: "unit-1",
          source_completed_at: "2026-05-10T08:00:00.000Z",
          completed_at: "2026-05-10T08:00:00.000Z",
          created_at: "2026-05-10T08:00:00.000Z",
          updated_at: "2026-05-10T08:00:00.000Z",
        },
      ],
      workouts: [
        {
          id: "workout-1",
          source_kind: "ai_session_v1",
          status: "accepted",
          generator_kind: "rule_engine_v1",
          source_fingerprint: "f0f0f0f0",
          title: "Threshold session",
          title_suggestions: ["Threshold session"],
          description: "Steady threshold session.",
          environment: "pool",
          pool_length_m: 25,
          session_type: "threshold_css",
          effort: "moderate",
          size_mode: "distance",
          target_distance_m: 2200,
          target_time_min: null,
          total_distance_m: 2200,
          estimated_duration_min: 46,
          base_pace_seconds_per_100: 128,
          used_css_pace_label: "1:58",
          allowed_strokes: ["freestyle"],
          equipment_allowlist: ["pull_buoy"],
          focus_text: "Breathing timing",
          goal_title: "Swim 1500m",
          constraint_text: "Keep the first half smooth.",
          warnings: [],
          steps: [
            {
              id: "step-1",
              category: "warmup",
              name: "Warmup swim",
            },
          ],
          generated_at: "2026-03-20T08:30:00.000Z",
          accepted_at: "2026-03-20T08:35:00.000Z",
          created_at: "2026-03-20T08:35:00.000Z",
          updated_at: "2026-03-20T08:40:00.000Z",
        },
      ],
      trainingActivityEvents: [
        {
          id: "training-activity-1",
          source_kind: "manual",
          activity_category: "workout",
          canonical_sport: "swimming",
          canonical_sub_sport: "pool_swim",
          mapping_status: "trusted",
          outcome: "completed_as_planned",
          activity_started_at: "2026-06-22T06:30:00.000Z",
          activity_ended_at: "2026-06-22T07:08:00.000Z",
          activity_local_date: "2026-06-22",
          activity_timezone: "Europe/Oslo",
          timezone_source: "manual",
          duration_seconds: 2280,
          distance_m: 1800,
          elevation_m: null,
          energy_kcal: null,
          average_heart_rate_bpm: null,
          training_load: null,
          planned_workout_instance_id: "planned-instance-1",
          workout_id: "workout-1",
          program_id: "program-1",
          completed_activity_event_id: "completed-activity-1",
          provider_activity_evidence_id: null,
          detail_kind: "swim_session_snapshot",
          detail_snapshot: { kind: "manual_actual_session_snapshot_v1" },
          support_diagnostics: {},
          created_at: "2026-06-22T07:10:00.000Z",
          updated_at: "2026-06-22T07:10:00.000Z",
        },
      ],
      providerConnections: [
        {
          id: "provider-connection-1",
          provider_key: "garmin_activity_api",
          status: "connected_metadata_only",
          provider_user_id: "garmin-user-1",
          provider_display_name: "Garmin Connect",
          connected_at: "2026-06-22T07:00:00.000Z",
          revoked_at: null,
          disabled_at: null,
          last_successful_sync_at: "2026-06-22T07:15:00.000Z",
          last_sync_error_code: null,
          redacted_metadata: { source: "activity_api" },
          created_at: "2026-06-22T07:00:00.000Z",
          updated_at: "2026-06-22T07:15:00.000Z",
        },
      ],
      providerActivityEvidence: [
        {
          id: "provider-activity-1",
          provider_connection_id: "provider-connection-1",
          import_run_id: "provider-import-run-1",
          provider_key: "garmin_activity_api",
          provider_activity_id: "garmin-activity-1",
          status: "needs_review",
          activity_started_at: "2026-06-22T06:30:00.000Z",
          activity_date: "2026-06-22",
          activity_type: "swimming",
          sport_type: "swimming",
          sub_sport_type: "pool",
          duration_seconds: 1800,
          distance_m: 1200,
          pool_length_m: 25,
          pool_length_unit: "m",
          file_state: "available_from_provider",
          available_file_kinds: ["fit"],
          redacted_summary: { source: "provider_summary" },
          first_seen_at: "2026-06-22T07:15:00.000Z",
          last_seen_at: "2026-06-22T07:15:00.000Z",
          created_at: "2026-06-22T07:15:00.000Z",
          updated_at: "2026-06-22T07:15:00.000Z",
        },
      ],
      providerImportRuns: [
        {
          id: "provider-import-run-1",
          provider_connection_id: "provider-connection-1",
          provider_key: "garmin_activity_api",
          run_kind: "manual_fixture",
          status: "completed_with_warnings",
          started_at: "2026-06-22T07:14:00.000Z",
          finished_at: "2026-06-22T07:15:00.000Z",
          total_activity_count: 1,
          imported_count: 1,
          duplicate_count: 0,
          malformed_count: 0,
          unsupported_count: 0,
          error_code: null,
          redacted_diagnostics: { warning: "needs_review" },
          created_at: "2026-06-22T07:14:00.000Z",
          updated_at: "2026-06-22T07:15:00.000Z",
        },
      ],
    });

    expect(payload).toEqual({
      generatedAt: "2026-02-17T12:00:00.000Z",
      schemaVersion: "2026-06-23-training-activity-export",
      user: {
        id: "user-1",
        email: "swimmer@example.com",
      },
      profile: {
        id: "user-1",
        email: "swimmer@example.com",
        createdAt: "2026-02-01T08:00:00.000Z",
        updatedAt: "2026-02-10T08:00:00.000Z",
      },
      athleteProfile: {
        id: "athlete-profile-1",
        displayName: "Poolside Stian",
        firstName: "Stian",
        lastName: "Vikra",
        ageBand: "35_44",
        createdAt: "2026-03-19T08:00:00.000Z",
        updatedAt: "2026-03-19T08:05:00.000Z",
      },
      trainingMetrics: [
        {
          id: "metric-1",
          metricKey: "css",
          unit: "seconds_per_100m",
          valueSeconds: 118,
          recordedOn: "2026-03-19",
          sourceNote: "400 + 200 test",
          createdAt: "2026-03-19T08:10:00.000Z",
          updatedAt: "2026-03-19T08:11:00.000Z",
        },
      ],
      trainingPreferences: {
        id: "pref-1",
        poolLengthM: 25,
        availableDays: ["monday", "wednesday"],
        preferredWeeklySessionCount: 5,
        preferredSessionMinutes: 60,
        createdAt: "2026-03-19T08:12:00.000Z",
        updatedAt: "2026-03-19T08:13:00.000Z",
      },
      personalRecords: [
        {
          id: "record-1",
          distanceM: 100,
          stroke: "freestyle",
          course: "pool_25m",
          timeCentiseconds: 6234,
          recordedOn: "2026-03-19",
          sourceNote: "Club night",
          createdAt: "2026-03-19T08:14:00.000Z",
          updatedAt: "2026-03-19T08:15:00.000Z",
        },
      ],
      entitlements: [
        {
          id: "ent-1",
          productId: "guide_0_1000m",
          purchaserEmail: "swimmer@example.com",
          source: "stripe_checkout",
          stripeCustomerId: "cus_123",
          stripeCheckoutSessionId: "cs_test_123",
          grantedAt: "2026-02-11T08:00:00.000Z",
          createdAt: "2026-02-11T08:00:00.000Z",
          updatedAt: "2026-02-11T08:00:00.000Z",
        },
      ],
      courseProgress: [
        {
          lessonId: "lesson-1",
          done: true,
          videoSeconds: 120,
          updatedAt: "2026-02-12T08:00:00.000Z",
        },
      ],
      guideProgress: [
        {
          guideSlug: "poolside",
          sectionId: "d01",
          completed: true,
          notes: "felt smooth",
          updatedAt: "2026-02-13T08:00:00.000Z",
        },
      ],
      guideSessionProgress: [
        {
          guideSlug: "0-1000m",
          sessionNumber: 1,
          completed: true,
          notes: "solid pacing",
          completedAt: "2026-02-14T08:00:00.000Z",
          updatedAt: "2026-02-14T08:10:00.000Z",
        },
      ],
      goals: [
        {
          id: "goal-1",
          title: "Swim 1000m",
          targetValue: 1000,
          targetUnit: "m",
          targetDate: "2026-03-01",
          status: "active",
          celebratedAt: null,
          createdAt: "2026-02-15T08:00:00.000Z",
          updatedAt: "2026-02-15T08:00:00.000Z",
        },
      ],
      trainingFocuses: [
        {
          id: "focus-1",
          goalId: "goal-1",
          title: "Longer exhale in the water",
          details: "Relax before rotating to breathe.",
          status: "open",
          isPrimary: true,
          contextType: null,
          contextRef: null,
          completedAt: null,
          archivedAt: null,
          createdAt: "2026-03-19T08:00:00.000Z",
          updatedAt: "2026-03-19T08:00:00.000Z",
        },
      ],
      trainingNotes: [
        {
          id: "note-1",
          goalId: "goal-1",
          focusId: "focus-1",
          noteType: "question",
          status: "answered",
          body: "Am I lifting my head before breathing?",
          answer: "Yes, keep one goggle in the water.",
          contextType: null,
          contextRef: null,
          resolvedAt: "2026-03-19T08:05:00.000Z",
          createdAt: "2026-03-19T08:00:00.000Z",
          updatedAt: "2026-03-19T08:05:00.000Z",
        },
      ],
      downloadLinks: [
        {
          id: "dl-1",
          entitlementId: "ent-1",
          expiresAt: "2026-02-20T08:00:00.000Z",
          usedAt: null,
          createdAt: "2026-02-15T09:00:00.000Z",
        },
      ],
      drylandSessions: [
        {
          id: "dryland-1",
          sourceKind: "manual",
          status: "draft",
          sessionKind: "strength",
          title: "Core strength",
          description: "Short dryland session.",
          legacyFocusText: "Brace the trunk first.",
          exercises: [
            {
              id: "exercise-1",
              title: "Plank",
              sets: [{ id: "set-1", holdSeconds: 45 }],
            },
          ],
          startedAt: null,
          completedAt: null,
          actualDurationSeconds: null,
          createdAt: "2026-05-08T08:00:00.000Z",
          updatedAt: "2026-05-08T08:10:00.000Z",
        },
      ],
      habitDefinitions: [
        {
          id: "habit-1",
          title: "Quit chips",
          notes: null,
          habitMode: "quit",
          habitType: "avoidance",
          category: "nutrition",
          targetOperator: "at_most",
          targetValueNumeric: 0,
          targetUnit: "times",
          targetTime: null,
          startDate: "2026-05-09",
          lastLapseDate: null,
          timerEnabled: false,
          timerTargetSeconds: null,
          cadencePeriod: "weekly",
          cadenceTargetCount: 2,
          cadenceDayPolicy: "fixed",
          scheduleDays: ["monday", "tuesday"],
          isPerfectDayItem: true,
          status: "active",
          sortOrder: 1,
          createdAt: "2026-05-09T08:00:00.000Z",
          updatedAt: "2026-05-09T08:10:00.000Z",
        },
      ],
      habitCheckIns: [
        {
          id: "habit-check-in-1",
          habitId: "habit-1",
          checkInDate: "2026-05-10",
          timezone: "Europe/Oslo",
          valueNumeric: null,
          valueBoolean: false,
          valueTime: null,
          note: null,
          status: "logged",
          sourceKind: "micro_session",
          sourceDrylandMicroPlanId: "22222222-2222-4222-8222-222222222222",
          sourceMicroBlockId: "unit-1",
          sourceCompletedAt: "2026-05-10T08:00:00.000Z",
          completedAt: "2026-05-10T08:00:00.000Z",
          createdAt: "2026-05-10T08:00:00.000Z",
          updatedAt: "2026-05-10T08:00:00.000Z",
        },
      ],
      workouts: [
        {
          id: "workout-1",
          sourceKind: "ai_session_v1",
          status: "accepted",
          generatorKind: "rule_engine_v1",
          sourceFingerprint: "f0f0f0f0",
          title: "Threshold session",
          titleSuggestions: ["Threshold session"],
          description: "Steady threshold session.",
          environment: "pool",
          poolLengthM: 25,
          sessionType: "threshold_css",
          effort: "moderate",
          sizeMode: "distance",
          targetDistanceM: 2200,
          targetTimeMin: null,
          totalDistanceM: 2200,
          estimatedDurationMin: 46,
          basePaceSecondsPer100m: 128,
          usedCssPaceLabel: "1:58",
          allowedStrokes: ["freestyle"],
          equipmentAllowlist: ["pull_buoy"],
          focusText: "Breathing timing",
          goalTitle: "Swim 1500m",
          constraintText: "Keep the first half smooth.",
          warnings: [],
          steps: [
            {
              id: "step-1",
              category: "warmup",
              name: "Warmup swim",
            },
          ],
          generatedAt: "2026-03-20T08:30:00.000Z",
          acceptedAt: "2026-03-20T08:35:00.000Z",
          createdAt: "2026-03-20T08:35:00.000Z",
          updatedAt: "2026-03-20T08:40:00.000Z",
        },
      ],
      trainingActivityEvents: [
        {
          id: "training-activity-1",
          sourceKind: "manual",
          activityCategory: "workout",
          canonicalSport: "swimming",
          canonicalSubSport: "pool_swim",
          mappingStatus: "trusted",
          outcome: "completed_as_planned",
          activityStartedAt: "2026-06-22T06:30:00.000Z",
          activityEndedAt: "2026-06-22T07:08:00.000Z",
          activityLocalDate: "2026-06-22",
          activityTimezone: "Europe/Oslo",
          timezoneSource: "manual",
          durationSeconds: 2280,
          distanceM: 1800,
          elevationM: null,
          energyKcal: null,
          averageHeartRateBpm: null,
          trainingLoad: null,
          plannedWorkoutInstanceId: "planned-instance-1",
          workoutId: "workout-1",
          programId: "program-1",
          completedActivityEventId: "completed-activity-1",
          providerActivityEvidenceId: null,
          detailKind: "swim_session_snapshot",
          detailSnapshot: { kind: "manual_actual_session_snapshot_v1" },
          supportDiagnostics: {},
          createdAt: "2026-06-22T07:10:00.000Z",
          updatedAt: "2026-06-22T07:10:00.000Z",
        },
      ],
      providerConnections: [
        {
          id: "provider-connection-1",
          providerKey: "garmin_activity_api",
          status: "connected_metadata_only",
          providerUserId: "garmin-user-1",
          providerDisplayName: "Garmin Connect",
          connectedAt: "2026-06-22T07:00:00.000Z",
          revokedAt: null,
          disabledAt: null,
          lastSuccessfulSyncAt: "2026-06-22T07:15:00.000Z",
          lastSyncErrorCode: null,
          redactedMetadata: { source: "activity_api" },
          createdAt: "2026-06-22T07:00:00.000Z",
          updatedAt: "2026-06-22T07:15:00.000Z",
        },
      ],
      providerActivityEvidence: [
        {
          id: "provider-activity-1",
          providerConnectionId: "provider-connection-1",
          importRunId: "provider-import-run-1",
          providerKey: "garmin_activity_api",
          providerActivityId: "garmin-activity-1",
          status: "needs_review",
          activityStartedAt: "2026-06-22T06:30:00.000Z",
          activityDate: "2026-06-22",
          activityType: "swimming",
          sportType: "swimming",
          subSportType: "pool",
          durationSeconds: 1800,
          distanceM: 1200,
          poolLengthM: 25,
          poolLengthUnit: "m",
          fileState: "available_from_provider",
          availableFileKinds: ["fit"],
          redactedSummary: { source: "provider_summary" },
          firstSeenAt: "2026-06-22T07:15:00.000Z",
          lastSeenAt: "2026-06-22T07:15:00.000Z",
          createdAt: "2026-06-22T07:15:00.000Z",
          updatedAt: "2026-06-22T07:15:00.000Z",
        },
      ],
      providerImportRuns: [
        {
          id: "provider-import-run-1",
          providerConnectionId: "provider-connection-1",
          providerKey: "garmin_activity_api",
          runKind: "manual_fixture",
          status: "completed_with_warnings",
          startedAt: "2026-06-22T07:14:00.000Z",
          finishedAt: "2026-06-22T07:15:00.000Z",
          totalActivityCount: 1,
          importedCount: 1,
          duplicateCount: 0,
          malformedCount: 0,
          unsupportedCount: 0,
          errorCode: null,
          redactedDiagnostics: { warning: "needs_review" },
          createdAt: "2026-06-22T07:14:00.000Z",
          updatedAt: "2026-06-22T07:15:00.000Z",
        },
      ],
    });
  });

  it("supports null profile and empty collections", () => {
    const payload = buildUserExportPayload({
      userId: "user-2",
      userEmail: null,
      generatedAt: "2026-02-17T12:00:00.000Z",
      profile: null,
      athleteProfile: null,
      trainingMetrics: [],
      trainingPreferences: null,
      personalRecords: [],
      entitlements: [],
      courseProgress: [],
      guideProgress: [],
      guideSessionProgress: [],
      goals: [],
      trainingFocuses: [],
      trainingNotes: [],
      downloadLinks: [],
      drylandSessions: [],
      habitDefinitions: [],
      habitCheckIns: [],
      workouts: [],
      trainingActivityEvents: [],
      providerConnections: [],
      providerActivityEvidence: [],
      providerImportRuns: [],
    });

    expect(payload.profile).toBeNull();
    expect(payload.athleteProfile).toBeNull();
    expect(payload.personalRecords).toEqual([]);
    expect(payload.entitlements).toEqual([]);
    expect(payload.trainingFocuses).toEqual([]);
    expect(payload.trainingNotes).toEqual([]);
    expect(payload.downloadLinks).toEqual([]);
    expect(payload.drylandSessions).toEqual([]);
    expect(payload.habitDefinitions).toEqual([]);
    expect(payload.habitCheckIns).toEqual([]);
    expect(payload.workouts).toEqual([]);
    expect(payload.trainingActivityEvents).toEqual([]);
    expect(payload.providerConnections).toEqual([]);
    expect(payload.providerActivityEvidence).toEqual([]);
    expect(payload.providerImportRuns).toEqual([]);
  });

  it("preserves future Habit definition values and child history in the private export", () => {
    type ExportInput = Parameters<typeof buildUserExportPayload>[0];
    type ExportHabitDefinition = ExportInput["habitDefinitions"][number];
    type ExportHabitCheckIn = ExportInput["habitCheckIns"][number];

    const buildDefinition = (
      id: string,
      overrides: Partial<ExportHabitDefinition>
    ): ExportHabitDefinition => ({
      id,
      title: `Private habit ${id}`,
      notes: `Private note ${id}`,
      habit_mode: "build",
      habit_type: "binary",
      category: "other",
      target_operator: "at_least",
      target_value_numeric: null,
      target_unit: null,
      target_time: null,
      start_date: "2026-08-31",
      last_lapse_date: null,
      timer_enabled: false,
      timer_target_seconds: null,
      cadence_period: "daily",
      cadence_target_count: 1,
      cadence_day_policy: "fixed",
      schedule_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      is_perfect_day_item: true,
      status: "active",
      sort_order: 1,
      created_at: "2026-08-31T08:00:00.000Z",
      updated_at: "2026-08-31T08:00:00.000Z",
      ...overrides,
    });
    const definitions = [
      buildDefinition("habit-future-type", {
        habit_type: "future_type" as ExportHabitDefinition["habit_type"],
      }),
      buildDefinition("habit-future-mode", {
        habit_mode: "future_mode" as ExportHabitDefinition["habit_mode"],
        sort_order: 2,
      }),
      buildDefinition("habit-future-status", {
        status: "future_status" as ExportHabitDefinition["status"],
        sort_order: 3,
      }),
      buildDefinition("habit-future-mixed", {
        habit_type: "future_type_mixed" as ExportHabitDefinition["habit_type"],
        habit_mode: "future_mode_mixed" as ExportHabitDefinition["habit_mode"],
        status: "future_status_mixed" as ExportHabitDefinition["status"],
        sort_order: 4,
      }),
    ];
    const checkIns: ExportHabitCheckIn[] = definitions.map((definition, index) => ({
      id: `check-${index + 1}`,
      habit_id: definition.id,
      check_in_date: "2026-08-31",
      timezone: "Europe/Oslo",
      value_numeric: null,
      value_boolean: true,
      value_time: null,
      note: `Private history ${index + 1}`,
      status: "logged",
      source_kind: index === 3 ? "micro_session" : "manual",
      source_dryland_micro_plan_id: index === 3 ? "micro-plan-1" : null,
      source_micro_block_id: index === 3 ? "micro-block-1" : null,
      source_completed_at: index === 3 ? "2026-08-31T09:00:00.000Z" : null,
      completed_at: "2026-08-31T09:00:00.000Z",
      created_at: "2026-08-31T09:00:00.000Z",
      updated_at: "2026-08-31T09:00:00.000Z",
    }));

    const payload = buildUserExportPayload({
      userId: "user-private-export",
      userEmail: "owner@example.com",
      generatedAt: "2026-09-01T08:00:00.000Z",
      profile: null,
      athleteProfile: null,
      trainingMetrics: [],
      trainingPreferences: null,
      personalRecords: [],
      entitlements: [],
      courseProgress: [],
      guideProgress: [],
      guideSessionProgress: [],
      goals: [],
      trainingFocuses: [],
      trainingNotes: [],
      downloadLinks: [],
      drylandSessions: [],
      habitDefinitions: definitions,
      habitCheckIns: checkIns,
      workouts: [],
      trainingActivityEvents: [],
      providerConnections: [],
      providerActivityEvidence: [],
      providerImportRuns: [],
    });

    expect(payload.schemaVersion).toBe("2026-06-23-training-activity-export");
    expect(
      payload.habitDefinitions.map(({ id, habitType, habitMode, status }) => ({
        id,
        habitType,
        habitMode,
        status,
      }))
    ).toEqual([
      {
        id: "habit-future-type",
        habitType: "future_type",
        habitMode: "build",
        status: "active",
      },
      {
        id: "habit-future-mode",
        habitType: "binary",
        habitMode: "future_mode",
        status: "active",
      },
      {
        id: "habit-future-status",
        habitType: "binary",
        habitMode: "build",
        status: "future_status",
      },
      {
        id: "habit-future-mixed",
        habitType: "future_type_mixed",
        habitMode: "future_mode_mixed",
        status: "future_status_mixed",
      },
    ]);
    expect(payload.habitCheckIns).toEqual(
      checkIns.map((row) =>
        expect.objectContaining({
          id: row.id,
          habitId: row.habit_id,
          note: row.note,
          sourceKind: row.source_kind,
          sourceDrylandMicroPlanId: row.source_dryland_micro_plan_id,
        })
      )
    );
  });
});
